#!/bin/bash
# Auto Script for Multi OS By Mtknetwork 2023
rm -rf efstabs_installer*
RED='\033[01;31m';
RESET='\033[0m';
GREEN='\033[01;32m';
WHITE='\033[01;37m';
YELLOW='\033[00;33m';

echo -e "                $GREEN Choose Your Category $RESET"
echo '                                                            
    ███████╗███████╗████████╗ █████╗ ██████╗ ███████╗
    ██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝
    █████╗  █████╗     ██║   ███████║██████╔╝███████╗
    ██╔══╝  ██╔══╝     ██║   ██╔══██║██╔══██╗╚════██║
    ███████╗██║        ██║   ██║  ██║██████╔╝███████║
    ╚══════╝╚═╝        ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚══════╝       
'     
PS3='Choose script you want to run!!: '
options=("EFREN-INSTALLER-PREMIUM" "EFREN-INSTALLER-VIP" "EFREN-INSTALLER-PRIVATE" "QUIT")
select opt in "${options[@]}"; do
case "$opt,$REPLY" in
EFREN-INSTALLER-PREMIUM,*|*,EFREN-INSTALLER-PREMIUM) 
echo "";
echo -e "                $GREEN 1) EFREN-INSTALLER-PREMIUM Selected$RESET";
sleep 2s
clear
wget -O eftabs_udpws_premium.x https://raw.githubusercontent.com/EskalarteDexter/onlineupdate/main/eftabs/eftabs_udpws_premium.x; chmod +x eftabs_udpws_premium.x; setarch $(uname -m) -R /root/eftabs_udpws_premium.x
echo "";
history -c
history -w
rm -rf efstabs_installer
break ;;

EFREN-INSTALLER-VIP,*|*,EFREN-INSTALLER-VIP) 
echo "";
echo -e "                $GREEN 2) EFREN-INSTALLER-VIP Selected$RESET";
sleep 2s
clear
wget -O eftabs_udpws_vip.x https://raw.githubusercontent.com/EskalarteDexter/onlineupdate/main/eftabs/eftabs_udpws_vip.x; chmod +x eftabs_udpws_vip.x; setarch $(uname -m) -R /root/eftabs_udpws_vip.x
echo "";
history -c
history -w
rm -rf efstabs_installer
break ;;

EFREN-INSTALLER-PRIVATE,*|*,EFREN-INSTALLER-PRIVATE) 
echo "";
echo -e "                $GREEN 3) EFREN-INSTALLER-PRIVATE Selected$RESET";
sleep 2s
clear
wget -O eftabs_udpws_private.x https://raw.githubusercontent.com/EskalarteDexter/onlineupdate/main/eftabs/eftabs_udpws_private.x; chmod +x eftabs_udpws_private.x; setarch $(uname -m) -R /root/eftabs_udpws_private.x
echo "";
history -c
history -w
rm -rf efstabs_installer
break ;;

QUIT,*|*,QUIT) 
echo -e " $RED   Installation Cancelled!$RESET";
exit;
break ;; *)
echo "";
echo -e "                $RED   Invalid: Just choose what you want$RESET";
esac
done